name: Deploy IAM Users with Terraform

on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.6.0
  TF_WORKING_DIR: .

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - run: terraform plan -out=tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Upload plan file
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}/tfplan
          if-no-files-found: error

  wait-for-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production
    steps:
      - run: echo "Awaiting manual approval..."

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: wait-for-approval
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Download tfplan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}

      - run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}